"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
API_DATA_URL = os.getenv("API_DATA_URL")

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_tailwind_cli",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

TAILWIND_CLI_PATH = BASE_DIR / "static" / "css" / "tailwind"
STATICFILES_DIRS = [BASE_DIR / "static"]

# daisyUI : télécharge le binaire « tailwindcss-extra » (Tailwind v4 + daisyUI)
# et compile depuis notre fichier source versionné (thème emerald). La sortie
# reste static/css/tailwind.css (défaut), donc {% tailwind_css %} est inchangé.
TAILWIND_CLI_USE_DAISY_UI = True
TAILWIND_CLI_SRC_CSS = "assets/css/source.css"


# ==============================================================================
# CONFIGURATION CELERY & REDIS
# ==============================================================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = (
    "Europe/Paris"  # Pour aligner les tâches planifiées sur ton fuseau horaire
)


# ==============================================================================
# CONFIGURATION CACHE & SESSIONS (REDIS)
# ==============================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# On demande à Django d'utiliser le cache Redis pour stocker les sessions
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# ==============================================================================
# CONFIGURATION CLIENT API (résilience réseau)
# ==============================================================================
# Timeouts httpx en secondes : connexion et lecture distingués.
API_CONNECT_TIMEOUT = float(os.getenv("API_CONNECT_TIMEOUT", "5.0"))
API_READ_TIMEOUT = float(os.getenv("API_READ_TIMEOUT", "15.0"))
# Politique de retry : uniquement erreurs transitoires + méthodes idempotentes.
# Nombre de rejeux au-delà de la tentative initiale (2 => 3 tentatives au total).
API_MAX_RETRIES = int(os.getenv("API_MAX_RETRIES", "2"))
# Base du backoff exponentiel en secondes (délai = backoff * 2 ** tentative).
API_RETRY_BACKOFF = float(os.getenv("API_RETRY_BACKOFF", "0.5"))


# ==============================================================================
# UPLOAD DE DOCUMENTS (relayés vers l'API, jamais stockés côté BFF)
# ==============================================================================
# Taille maximale acceptée avant relais vers l'API (octets). Configurable.
DOCUMENT_UPLOAD_MAX_SIZE = int(
    os.getenv("DOCUMENT_UPLOAD_MAX_SIZE", str(10 * 1024 * 1024))
)  # 10 Mo par défaut
# Types MIME autorisés (la validation serveur fait autorité).
DOCUMENT_UPLOAD_ALLOWED_TYPES = ["application/pdf", "image/png", "image/jpeg"]
# Extensions correspondantes, pour l'attribut `accept` et la validation client.
DOCUMENT_UPLOAD_ALLOWED_EXTENSIONS = [".pdf", ".png", ".jpg", ".jpeg"]


# ==============================================================================
# LOGGING (monitoring des erreurs de communication avec l'API)
# ==============================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        # Retries et échecs définitifs de la couche cliente API.
        "clients": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
